version: '3.8'

services:
  central-de-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: central-de-app
    ports:
      - "8885:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
